image:
  api_token: AhUiTb_1C9bJJJBbIuwuHOZctXHnvyeVmM5jGtErwZ5U9IYe96rJEGZ-QwIY_J9V
  img_api: bing
  img_url: http://t0.tiles.virtualearth.net/tiles/a{q}.png?g=854&mkt=en-US&token={token}
  zoom: 18
osm:
  api: ohsome
  bboxes:
  - 10.23730516433716
  - 5.6593555522870975
  - 10.242519378662111
  - 5.664864621342375
  tags:
  - key: building
    label: building
    value: ''
  timestamp: 2022-12-31
  types: polygon
  url: https://api.ohsome.org/v1/elements/geometry
project:
  name: inference
  project_time: 2023-05-03
  task: object detection
  workspace: ./data
